In [1]:
# Set-3 Mathematical Computing with Python (numpy)

# 3.1 Create an array of numbers from one to twenty in reverse order.
import numpy as np
arr = np.arange(20, 0, -1)
print(arr)


[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [2]:
# 3.2 Create an array of 10 numbers which is evenly spaced in the range of 1 to 5.
arr = np.linspace(1, 5, 10)
print(arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [3]:
# 3.3 Create an array of 10 numbers which is evenly spaced in the range of 1 to 5 on log scale.
arr = np.logspace(1, 5, 10)
print(arr)

[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


In [4]:
# 3.4 Create an array of 10 random numbers in the range of 200 to 300.
arr = np.random.randint(200, 300, 10)
print(arr)

[258 239 295 206 246 232 213 262 253 294]


In [5]:
# 3.5 Create a 2D array of size 2X3 with all elements filled with 8
arr = np.full((2, 3), 8)
print(arr)

[[8 8 8]
 [8 8 8]]


In [6]:
# 3.6 Create a 2D array of size 4X3 with all elements in the range of 1 to 12 and perform following operations:
# a. Display the created array
# b. Display the second row of the created array.
# c. Display the second column of the created array.
# d. Display alternate columns of the created array.
# e. Display second and fourth row of the created array
# f. Display odd rows and even column.

arr = np.arange(1, 13).reshape(4, 3)

print("The created array is:")
print(arr)

print("The second row of the created array is:")
print(arr[1])

print("The second column of the created array is:")
print(arr[:, 1])

print("Alternate columns of the created array are:")
print(arr[:, ::2])

print("Second and fourth row of the created array are:")
print(arr[[1, 3]])

print("Odd rows and even column of the created array are:")
print(arr[::2, 1])

The created array is:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
The second row of the created array is:
[4 5 6]
The second column of the created array is:
[ 2  5  8 11]
Alternate columns of the created array are:
[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]
Second and fourth row of the created array are:
[[ 4  5  6]
 [10 11 12]]
Odd rows and even column of the created array are:
[2 8]


In [8]:
# 3.7 Write a Python program to generate a 1-D array containing 100
# values, where each value has to be 10, 20, 50 or 75.
# a. The probability for the value to be 10 is set to be 0.4
# b. The probability for the value to be 20 is set to be 0.2
# c. The probability for the value to be 50 is set to be 0.1
# d. The probability for the value to be 75 is set to be 0.3

arr = np.random.choice([10, 20, 50, 75], 100, p=[0.4, 0.2, 0.1, 0.3])
print(arr)


[10 10 75 20 10 50 10 75 75 75 75 75 10 20 75 10 75 10 10 20 20 10 10 75
 20 10 10 10 20 10 10 75 75 75 10 75 75 20 10 10 10 20 75 10 75 10 10 75
 75 20 10 20 10 75 10 10 10 10 75 20 75 75 10 20 50 75 20 20 20 10 50 10
 75 10 10 50 20 75 10 10 10 50 10 10 50 50 20 10 75 20 75 10 75 50 10 10
 20 20 10 10]
