In [2]:
# 5.1 Create an array of numbers from one to twenty in reverse order.
import numpy as np
arr1 = np.arange(20, 0, -1)
print(arr1)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [4]:
# 5.2 Create an array of 10 numbers which is evenly spaced in the range of 1 to 5.
arr2 = np.linspace(1, 5, 10)
print(arr2)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [6]:
# 5.3 Create an array of 10 numbers which is evenly spaced in the range of 1 to 5 on log scale.
arr3 = np.logspace(1, 5, 10)
print(arr3)

[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


In [7]:
# 5.4 Create an array of 10 random numbers in the range of 200 to 300.
arr4 = np.random.randint(200, 300, 10)   
print(arr4)

[282 217 244 257 282 242 248 254 269 264]


In [8]:
# 5.5 Create a 2D array of size 2X3 with all elements filled with 8
arr5 = np.full((2, 3), 8)
print(arr5)

[[8 8 8]
 [8 8 8]]


In [12]:
# 5.6 Create a 2D array of size 4X3 with all elements in the range of 1 to 12 and perform following operations:
arr6 = np.arange(1, 13).reshape(4, 3)
# Display the created array. 
print("Created array: \n")
print(arr6)
# Display the second row of the created array.
print("Second row of the created array: \n")
print(arr6[1])
# Display the second column of the created array.
print("Second column of the created array: \n")
print(arr6[:, 1])
# Display alternate columns of the created array.
print("Alternate columns of the created array: \n")
print(arr6[:, ::2])
# Display second and fourth row of the created array
print("Second and fourth row of the created array: \n")
print(arr6[1::2])
# Display odd rows and even column.
print("Odd rows and even column of the created array: \n")
print(arr6[::2, 1::2])

Created array: 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Second row of the created array: 

[4 5 6]
Second column of the created array: 

[ 2  5  8 11]
Alternate columns of the created array: 

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]
Second and fourth row of the created array: 

[[ 4  5  6]
 [10 11 12]]
Odd rows and even column of the created array: 

[[2]
 [8]]
